basePath: /api/v1/
definitions:
  controllers.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
      more_info:
        example: http://
        type: string
    type: object
  models.Show:
    properties:
      api_url:
        example: http://adad.ad/se
        type: string
      decription:
        example: Show about x
        type: string
      genre:
        example: "2019-12-22"
        type: string
      imageUrl:
        example: http://adad.ad/se
        type: string
      name:
        example: Show Name
        type: string
      page_url:
        example: http://adad.ad/se
        type: string
      seasons:
        items:
          type: Season
        type: array
      service:
        type: string
      slug:
        example: show_name
        type: string
      updatedAt:
        example: "2019-12-22"
        type: string
    type: object
info:
  contact:
    email: support@egeback.se
    name: API Support
    url: http://xxxx.xxx.xx
  description: API including SVT and TV4 Play
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  title: Play API
  version: 1.0.5
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
        "500":
          description: ok
          schema:
            type: string
      summary: ping common
      tags:
      - common
  /shows:
    get:
      consumes:
      - application/json
      description: get shows
      parameters:
      - description: pretty print show
        format: bool
        in: query
        name: prettyPrint
        type: string
      - description: show seasons
        format: bool
        in: query
        name: showSeasons
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Show'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: List shows
      tags:
      - shows
  /shows/{slug}:
    get:
      consumes:
      - application/json
      description: get show by slug
      parameters:
      - description: Show ID
        in: path
        name: slug
        required: true
        type: string
      - description: pretty print show
        format: bool
        in: query
        name: prettyPrint
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Show'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Show an show
      tags:
      - shows
swagger: "2.0"
