basePath: /api/v1/
definitions:
  controllers.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
      more_info:
        example: http://
        type: string
    type: object
  models.Episode:
    properties:
      duration:
        type: number
      imageUrl:
        type: string
      longDescription:
        type: string
      name:
        type: string
      number:
        type: string
      slug:
        type: string
      svtId:
        type: string
      url:
        type: string
      validFrom:
        type: string
      validTo:
        type: string
      variants:
        items:
          $ref: '#/definitions/models.Variant'
        type: array
      videoSvtId:
        type: string
    type: object
  models.Season:
    properties:
      'episodes groups:':
        items:
          $ref: '#/definitions/models.Episode'
        type: array
      'id groups:':
        type: string
      'name groups:':
        type: string
    type: object
  models.Show:
    properties:
      decription:
        example: Show about x
        type: string
      genre:
        example: "2019-12-22"
        type: string
      imageUrl:
        example: http://adad.ad/se
        type: string
      name:
        example: Show Name
        type: string
      seasons:
        items:
          $ref: '#/definitions/models.Season'
        type: array
      slug:
        example: show_name
        type: string
      updatedAt:
        example: "2019-12-22"
        type: string
      url:
        example: http://adad.ad/se
        type: string
    type: object
  models.Variant:
    properties:
      svtId:
        type: string
      url:
        type: string
    type: object
info:
  contact:
    email: support@egeback.se
    name: API Support
    url: http://xxxx.xxx.xx
  description: API including SVT and TV4 Play
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  title: Play Media API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
        "500":
          description: ok
          schema:
            type: string
      summary: ping common
      tags:
      - common
  /show/{slug}:
    get:
      consumes:
      - application/json
      description: get show by slug
      parameters:
      - description: Show ID
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Show'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Show an show
      tags:
      - shows
  /shows:
    get:
      consumes:
      - application/json
      description: get shows
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Show'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: List shows
      tags:
      - shows
swagger: "2.0"
